version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/setup.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
